name: App Deployment
on:
  push:
    branches: [ master ]
env:
  #PUBLIC_API_URL: "https://api."
  #PUBLIC_EDITOR_APP_URL: "https://"
  #PUBLIC_AVATAR_BASE_URL: "https://"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: actions/setup-node@v1
      with:
        node-version: 18
    
    - name: Setup Environment
      run: |
        pnpm install
    - name: Generate meta and build
      run: |
        npm run generate-renderer
        npm run build
        touch ./dist/.nojekyll
        echo 'printdesk.xyz' > ./dist/CNAME
    - name: Deploy to GH Pages
      run: |
        git config user.email "princekunal652@gmail.com"
        git config user.name "Prince Kunal"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy